version: '2'
services:

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./docker/database/dumps:/dumps:rw,cached
      - ./docker/database/data/mysql-master:/var/lib/mysql:rw,cached
      - ./docker/database/config/mysql-master:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3307:3306"
    restart: always